feat: basic ERD project page styling
KMU-FlowERD/front-end pull request #21
Opened 2024-09-17 14:58 UTC by dbtkdfhr

## Overview
- 프로젝트 페이지를 피그마에 맞게 UI 제작
- 각 UI를 컴포넌트화

## Issues
- #18

2024-09-17 14:59 UTC, dbtkdfhr commented on src/components/implements-icon/IconComponent.tsx
아이콘 컴포넌트를 지금처럼 한 파일로 제작할지 각 아이콘 별로 파일을 작성할 지 의견 바랍니다

2024-09-18 03:30 UTC, cjeongmin commented on src/components/implements-icon/IconComponent.tsx
아이콘 컴포넌트라기보다는 일반적인 아이콘 에셋들은 따로 분리하는게 좋아보이고, 릴레이션 매핑을 위한 아이콘들은 현재처럼 svg를 직접 사용하는 것도 괜찮아 보입니다.

2024-09-18 03:34 UTC, cjeongmin requested changes
그리고 리뷰 중에 열린 대화는 리뷰어가 resolve 하는 것을 원칙으로 합니다. 이모지나 댓글을 통해 항상 모든 대화의 마지막을 리뷰이가 담담하게 해주세요.

2024-09-18 03:34 UTC, cjeongmin commented on src/page/erd-project.page.tsx
> +import styled from '@emotion/styled';
`TableComponent`를 import 하는 부분이 현재 문제가 있는 것 같습니다. 먼저 해결해 주세요.

2024-09-18 13:20 UTC, dbtkdfhr commented on src/page/erd-project.page.tsx
> +import styled from '@emotion/styled';
수정했습니다!

2024-09-18 13:22 UTC, dbtkdfhr commented on src/page/erd-project.page.tsx
> +import styled from '@emotion/styled';
수정했습니다!

2024-09-19 03:28 UTC, cjeongmin requested changes
**p2**

여러 컴포넌트에서 이름이 **Component 로 지금 네이밍되는데 Component 이름이 붙는게 좋아보이진 않습니다. Component 라는 suffix는 제거하고 더 명확하게 이름을 지어주세요.

예를 들어, `ImplementComponent` 를 예시를 들어보면 이름만 보아서는 사실 무슨 역할인지 잘 모를 수 있을 것 같습니다. 해당 컴포넌트가 그리기 도구를 제공하는 것으로 보이는데 `ErdDrawingTools` 와 같이 하면 좋을 것 같습니다.

2024-09-19 03:28 UTC, cjeongmin commented on src/app/globals.css
> +  min-width: 375px;
**p1**


해당 파일이 다른 프로젝트의 파일을 그대로 가져온 것 같은데.. 이 속성이 이 프로젝트에서도 있는게 맞는지 생각해봐주세요

2024-09-19 03:28 UTC, cjeongmin commented on src/components/implements-icon/icon.type.ts
> +export enum IconType {
**p3**

Typescript 에서 enum 사용에 대해 알아보고 다른 방법은 없을지 생각해봐주세요.

2024-09-19 08:52 UTC, dbtkdfhr commented on src/components/implements-icon/icon.type.ts
> +export enum IconType {
enum을 안쓰는 이유 확인 했습니다.
enum 대신에 union type으로 수정 했습니다

2024-09-19 08:53 UTC, dbtkdfhr commented on src/app/globals.css
> +  min-width: 375px;
마루 css파일을 가져와서 테스트 하다가 실수로 그대로 넘겼네요 기존 globals.css 파일에서 width height만 수정하는 방향으로 바꿨습니다

2024-09-19 11:19 UTC, cjeongmin requested changes

2024-09-19 11:19 UTC, cjeongmin commented on src/app/globals.css
아까 이야기했던 속성만 변경해도 좋았을텐데, 지금은 또 `Next.js` 의 기본 css를 모두 적용하고 있는게 맞는지 생각해보면 좋을 것 같습니다.

이 부분은 나중에 불필요하면 수정하면 좋을 것 같아요.

2024-09-19 11:19 UTC, cjeongmin commented on src/components/implements-icon/icon.type.ts
> +export type IconType = 'IOBO' | 'IOBM' | 'IMBM' | 'NIOBO' | 'NIOBM' | 'NIMBM';
enum 타입에서 유니온 타입으로 변경된건 좋습니다.

근데, 여기서 유니온 타입에 들어가는 타입들의 이름이 줄여서 사용하면 나중에 알아보기 어렵지 않을까요? 저는 기존 방식이 훨씬 좋다고 생각합니다.

`IOBO` → `IdentifyOneToOne`

2024-09-19 11:20 UTC, cjeongmin commented on src/app/globals.css
이 부분은 지금 안 해도 됩니다 👍🏼

2024-09-19 11:32 UTC, dbtkdfhr commented on src/components/implements-icon/icon.type.ts
> +export type IconType = 'IOBO' | 'IOBM' | 'IMBM' | 'NIOBO' | 'NIOBM' | 'NIMBM';
좋은 생각이네요 이 부분 수정했습니다

2024-09-19 11:35 UTC, cjeongmin approved these changes
LGTM 👍🏼

2024-09-19 11:37 UTC, merged