feat: connect ERD state, action and UI
KMU-FlowERD/front-end pull request #28
Opened 2024-10-12 14:37 UTC by dbtkdfhr

## Overview
- ERD 프로젝트의 상태와 액션 UI에 연결
- 테이블 메뉴 화면 구현
- 컬럼 수정 화면 구현
- 테이블과 관계 드로잉 구현

## Issues
- #22

2024-10-13 07:02 UTC, cjeongmin requested changes
많은 업데이트가 있어서 코멘트도 그만큼 많네요. 👍🏼추가로 하고싶은건 styles 변수에 각 스타일마다 공백 한 줄 정도 있으면 좋을 것 같습니다. :)

2024-10-16 09:52 UTC, dbtkdfhr commented on src/components/implements-icon/ArrowIcon.tsx
> +      {Icon(fill)}
`<Icon fill={fill} />`로 수정하였습니다

2024-10-16 09:52 UTC, dbtkdfhr commented on src/components/implements-icon/MemoIcon.tsx
> +      {Icon(fill)}
`<Icon fill={fill} />`로 수정하였습니다

2024-10-16 09:53 UTC, dbtkdfhr commented on src/components/implements-icon/RelationshipIcons.tsx
> +      {Icon(type, fill)}
`<Icon fill={fill} />`로 수정하였습니다
IdentifyOneToOne 등 아이콘을 파일 분리 하였습니다

2024-10-16 09:53 UTC, dbtkdfhr commented on src/components/implements-icon/TableIcon.tsx
> +      {Icon(fill)}
`<Icon fill={fill} />`로 수정하였습니다

2024-10-16 09:53 UTC, dbtkdfhr commented on src/components/ColumnEditMenu.tsx
> +  const pfkColumns = tableColumns.filter((val) => val.keyType === 'pk/fk');
pfkfColumns로 이름 수정하였습니다.

2024-10-16 09:54 UTC, dbtkdfhr commented on src/components/ColumnEditMenu.tsx
> +      ))}
pkColumns, fkColumns 등 따로 컴포넌트 제작하여 폴더화 하였습니다.

2024-10-16 09:54 UTC, dbtkdfhr commented on src/components/ConnectLine.tsx
> +  // getEndIDEFCircle,
무의미한 주석들과 코드 모두 제거했습니다.

2024-10-16 09:54 UTC, dbtkdfhr commented on src/components/Relationship.tsx
> +function getRelation(
getRelation 함수의 필요성이 없는 거 같아 삭제하였습니다.

2024-10-16 09:54 UTC, dbtkdfhr commented on src/components/Relationship.tsx
> +  const mineMapping: Map<ERDTable['id'], number> = new Map();
무의미한 주석들과 코드 모두 제거했습니다.

2024-10-16 09:56 UTC, dbtkdfhr commented on src/components/Relationship.tsx
> +      }
top의 네이밍이 이상한 거 같아 sortVal로 수정 하였습니다.

2024-10-16 09:56 UTC, dbtkdfhr commented on src/components/Table.tsx
>  }) {
인터페이스 분리 하였습니다.

2024-10-16 09:56 UTC, dbtkdfhr commented on src/components/Table.tsx
> +  const pfkColumns = table.columns.filter((val) => val.keyType === 'pk/fk');
pkfkColumn로 네이밍 수정 하였습니다

2024-10-16 09:58 UTC, dbtkdfhr commented on src/features/table-mapping/table-mapping.helper.ts
> +export type TableDirectionChild = Map<
table-mapping.type.ts 파일로 분리 하였고
네이밍 수정 하였습니다

2024-10-16 09:58 UTC, dbtkdfhr commented on src/features/erd-project/erd-project.slice.ts
> +export type KeyType = 'pk' | 'fk' | 'pk/fk';
잘못 변경된 거 같아요.
다시 수정하였습니다

2024-10-16 09:59 UTC, dbtkdfhr commented on src/page/erd-project.page.tsx
> +  // childTables: Set<string>,
불필요한 주석 제거 하였습니다.

2024-10-16 09:59 UTC, dbtkdfhr commented on src/page/erd-project.page.tsx
> +        )}
getTable 함수 삭제 하였습니다.

2024-10-17 09:14 UTC, cjeongmin commented on src/components/column-edit/index.ts
> +export * from './PkFkColumns';
이 4개는 외부로 내보낼 필요가 있을까요?

2024-10-17 09:17 UTC, cjeongmin commented on src/components/implements-icon/index.ts
> +export * from './NonIdentifyManyToManyIcon';
이 6개는 내부에서만 사용되는 것 같은데 외부로 내보내야할 이유가 있을까요?

2024-10-17 09:26 UTC, cjeongmin commented on src/components/table/FkColumns.tsx
이건 잘못된 것 같아요. 의도는 이해됩니다. FkColumns, PkColumns, PkFkColumns 컴포넌트 모두 Columns 컴포넌트와 같은 역할을 하지만 오로지 명시적으로 차이를 주려고 한 것으로 만든거로 해석이 됩니다.

그러면, 해당 목적을 이루기 위해서는 이 방법은 잘못되었다고 생각이 듭니다. 나중에 Columns 컴포넌트가 변경되면 어떻게 될까요? 다른 방법으로 하는게 더 좋을 것 같다고 생각이 듭니다.

사실 저라면, 의미론적으로 굳이 구분하지 않아도 된다고 생각합니다. Columsn에 넘어가는 데이터가 이미 다르니까 구분된다고 생각해요. 근데 명시적으로 차이를 주려고 한거고, 그 방법에 대해 다시 생각해보면 좋겠습니다.

2024-10-17 09:27 UTC, cjeongmin commented on src/components/table/Table.tsx
> +}
여기에 있는 많은 액션들은 나중에 사라지겠죠?

2024-10-17 09:27 UTC, cjeongmin commented on src/components/table/TableMenu.tsx
> +  createColumn: (table: ERDTable, isPk: boolean) => void;
여기 두 개도 나중에는 사라지는거겠죠?

2024-10-17 09:28 UTC, cjeongmin commented on src/components/table/index.ts
> +export * from './PkFkColumns';
이 4개도 내부에서만 사용되는거 아닌가요? 외부로 내보낼 이유가 없어보입니다.

2024-10-17 09:29 UTC, cjeongmin commented on src/components/index.ts
> +export * from './ConnectLine';
이 부분도 내부에만 사용되는 것 같네요.

2024-10-17 10:07 UTC, dbtkdfhr commented on src/components/table/Table.tsx
> +}
네 이 부분들은 나중에 사라질 액션들입니다

2024-10-17 10:07 UTC, dbtkdfhr commented on src/components/table/TableMenu.tsx
> +  createColumn: (table: ERDTable, isPk: boolean) => void;
네 이 부분들은 나중에 사라질 액션들입니다

2024-10-17 10:14 UTC, dbtkdfhr commented on src/components/column-edit/index.ts
> +export * from './PkFkColumns';
외부에서 쓰이지 않는 export는 제외 했습니다

2024-10-17 10:14 UTC, dbtkdfhr commented on src/components/implements-icon/index.ts
> +export * from './NonIdentifyManyToManyIcon';
외부에서 쓰이지 않는 export는 제외 했습니다

2024-10-17 10:14 UTC, dbtkdfhr commented on src/components/table/FkColumns.tsx
props로 주는 변수 명에 따라 충분히 구분이 가능할 거라고 생각해 Column 컴포넌트로 통일 하였습니다

2024-10-17 10:14 UTC, dbtkdfhr commented on src/components/table/index.ts
> +export * from './PkFkColumns';
외부에서 쓰이지 않는 export는 제외 했습니다

2024-10-17 10:15 UTC, dbtkdfhr commented on src/components/index.ts
> +export * from './ConnectLine';
외부에서 쓰이지 않는 export는 제외 했습니다

2024-10-17 10:38 UTC, cjeongmin approved these changes
LGTM

2024-10-17 10:39 UTC, merged