[FLOW-13] feat: add relation delete and nullable menu
KMU-FlowERD/front-end pull request #31
Opened 2024-10-19 15:26 UTC by dbtkdfhr

## Overview
관계가 그려진 선을 우클릭 할 시 생성되는 메뉴창을 만들고 삭제와 nullable을 추가 했습니다.

2024-10-20 08:22 UTC, cjeongmin commented on src/components/ConnectLine.tsx
> +      );
궁금해서 질문하는건데, 그냥 사용성을 위해서 따로 선을 하나 더 그리고, 실제로 더 크게 그리는건가요??

2024-10-20 08:24 UTC, cjeongmin commented on src/components/Relationship.tsx
제가 보기엔 지금 데이터가 그리기 위한 데이터와 컨텍스트 메뉴를 컨트롤하기 위한 코드가 혼용되어 나타나고 있습니다.

커스텀 훅에 대해 찾아보시고, 해당 부분을 적용해서 논리적으로 두 데이터를 나누면 더 좋은 코드가 될 것 같아요.

2024-10-20 08:26 UTC, cjeongmin commented on src/components/RelationshipMenu.tsx
> +  };
early return을 사용하는게 더 보기 좋을 것 같습니다.

2024-10-20 08:27 UTC, cjeongmin commented on src/components/ConnectLine.tsx
> +      );
궁금해서 질문하는건데, 그냥 사용성을 위해서 따로 선을 하나 더 그리고, 실제로 더 크게 그리는건가요??

2024-10-20 08:28 UTC, cjeongmin requested changes

2024-10-20 08:28 UTC, cjeongmin commented on src/components/Relationship.tsx
제가 보기엔 지금 데이터가 그리기 위한 데이터와 컨텍스트 메뉴를 컨트롤하기 위한 코드가 혼용되어 나타나고 있습니다.

커스텀 훅에 대해 찾아보시고, 해당 부분을 적용해서 논리적으로 두 데이터를 나누면 더 좋은 코드가 될 것 같아요.

2024-10-20 08:28 UTC, cjeongmin commented on src/components/ConnectLine.tsx
> +      );
궁금해서 질문하는건데, 그냥 사용성을 위해서 따로 선을 하나 더 그리고, 실제로 더 크게 그리는건가요??

2024-10-20 08:28 UTC, cjeongmin commented on src/components/RelationshipMenu.tsx
> +  };
early return을 사용하는게 더 보기 좋을 것 같습니다.

2024-10-20 13:55 UTC, dbtkdfhr commented on src/components/Relationship.tsx
그리기 위한 데이터 내용과 컨텍스트 메뉴를 훅으로 분리하여 리펙토링 하였습니다.

2024-10-20 13:55 UTC, dbtkdfhr commented on src/components/ConnectLine.tsx
> +      );
보이는 선과 우클릭을 할 수 있는 범위를 위한 라인을 따로 잡고 배경색을 투명색으로 주었습니다.

2024-10-20 13:56 UTC, dbtkdfhr commented on src/components/RelationshipMenu.tsx
> +  };
early return으로 수정 하였습니다

2024-10-20 16:02 UTC, cjeongmin requested changes

2024-10-20 16:02 UTC, cjeongmin commented on src/components/Relationship.tsx
> +      )}
지금 RelationshipMenu 컴포넌트에 많은 props를 전달하고 있는데 어떤가요? 보기 좋은가요? 만약, 이게 더 길어지면 어떻게 될까요? 또한, contextMenu의 존재 여부에 따라 RelationshipMenu 컴포넌트를 보여주고 있는데, 이를 감출 수 없을까요?

제가 생각했을 때 여기에서 커스텀 훅을 사용하는 이유는 ConnectLine에 openContextMenu 함수를 전달해야하고 RelationshipMenu 컴포넌트에도 그와 관련된 많은 props를 전달해야하기 때문입니다.

전역 상태로 두기엔 너무 지역적으로 사용되는 부분이고, 그렇다면 어떻게 해결하는게 좋을까요? 이와 관련된 방법이 있어서 한 번 찾아보면 좋을 것 같습니다. 코드가 더 명확하고 관심사가 분리될 것으로 보여요.

2024-10-20 16:02 UTC, cjeongmin commented on src/components/RelationshipMenu.tsx
> +  };
early return이 적용 안 되어 있습니다... 단순히 switch문을 if문으로 분해만 된 것으로 보여요.

2024-10-20 16:15 UTC, cjeongmin commented on src/components/Relationship.tsx
> +      )}
일단 시험 공부 먼저하고 모르겠다면 이 부분은 저한테 물어봐주세요.

2024-10-21 10:34 UTC, cjeongmin approved these changes
LGTM

2024-10-21 10:35 UTC, merged