[Flow-6]: add update canvas size and scroll using drag
KMU-FlowERD/front-end pull request #40
Opened 2024-10-26 12:25 UTC by dbtkdfhr

## Overview
- 테이블 위치, 크기에 따라 캔버스 사이즈 업데이트 액션을 연결 하였습니다.
- 마우스 휠 뿐만 아니라 드래그를 이용한 화면 이동을 구현 하였습니다.
- erd-project-page 파일을 리펙토링 하였습니다.

2024-10-26 13:34 UTC, cjeongmin commented
PR 이름 수정해주세용

2024-10-26 13:37 UTC, cjeongmin commented
다른 PR 참고해서 수정 부탁드립니다. 조금 달라용

2024-10-26 17:49 UTC, cjeongmin requested changes

2024-10-26 17:49 UTC, cjeongmin commented on src/components/table/Table.tsx
이 파일의 코드를 보면 개선점들이 많은 것 같습니다.

2024-10-26 17:49 UTC, cjeongmin commented on src/features/erd-page/erd-project-page.hoos.ts
파일 이름에 오타 있습니다.

2024-10-26 17:49 UTC, cjeongmin commented on src/features/erd-page/erd-project-page.hoos.ts
> +}
커스텀 훅으로 뺀 이유가 뭘까요?

2024-10-26 17:50 UTC, cjeongmin requested changes

2024-10-26 17:50 UTC, cjeongmin commented on src/app/globals.css
> -  height: 100dvh;
`width`, `height` 의 크기 설정을 제거한 이유는 뭘까요?

2024-10-27 06:36 UTC, dbtkdfhr commented on src/components/table/Table.tsx
Table 컴포넌트는 리펙토링을 한 번 하도록 하겠습니다.

2024-10-27 06:36 UTC, dbtkdfhr commented on src/features/erd-page/erd-project-page.hoos.ts
감사합니다 수정하였습니다

2024-10-27 06:36 UTC, dbtkdfhr commented on src/features/erd-page/erd-project-page.hoos.ts
> +}
원래 중간에 내용이 있다가 뺀 상태라 필요없는 훅이여서 삭제 하였습니다.

2024-10-27 06:37 UTC, dbtkdfhr commented on src/app/globals.css
> -  height: 100dvh;
globals.css 파일을 다루다가 다시 안넣었나 보네요
수정 하였습니다.

2024-10-28 08:12 UTC, cjeongmin approved these changes
LGTM

2024-10-28 08:13 UTC, merged