[FLOW-24] feat: add many to many mapping
KMU-FlowERD/front-end pull request #43
Opened 2024-10-26 15:41 UTC by dbtkdfhr

## Overview
- n:m 매핑 기능을 추가 하였습니다.

2024-10-26 17:53 UTC, cjeongmin commented
특정 작업을 다른 브랜치에서 이어서 하면, 파일 변경 사항들이 모두 중복됩니다.

이 부분에 대해서 프로젝트 초기에 이야기 했습니다...

2024-10-26 18:02 UTC, cjeongmin requested changes

2024-10-26 18:02 UTC, cjeongmin commented on src/page/erd-project/erd-project.page.tsx
> +      const mappingTable = {
이런 경우엔 실수를 줄이기 위해서 타입을 명시하는게 좋지 않을까요?

2024-10-27 06:44 UTC, dbtkdfhr commented on src/page/erd-project/erd-project.page.tsx
> +      const mappingTable = {
감사합니다 수정 하였습니다.

2024-10-28 08:55 UTC, cjeongmin approved these changes
LGTM

2024-10-28 08:55 UTC, merged